services:
  app:
    build: . # 使用同一個專案目錄中的 Dockerfile 建立映像
    # image: node:20.16.0 官方映像
    working_dir: /app
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=CRM
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=CRM
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
